# Generated by Django 4.2.16 on 2024-12-10 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0047_alter_twitterserviceaccount_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterUserAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_token', models.CharField(max_length=255)),
                ('oauth_token_secret', models.CharField(max_length=255)),
                ('authorized_at', models.DateTimeField(auto_now_add=True)),
                ('service_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.twitterserviceaccount')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'service_account')},
            },
        ),
    ]
