# Generated by Django 4.2.16 on 2024-12-15 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_task_email_send_error_task_email_sent_and_more'),
        ('twitter_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('ERROR', 'Error'), ('RATE_LIMIT', 'Rate Limit')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_user', models.CharField(blank=True, max_length=255, null=True)),
                ('service_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='api.twitterserviceaccount')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='api.task')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitter_action_logs', to='api.userprofile')),
            ],
            options={
                'verbose_name': 'Twitter Action Log',
                'verbose_name_plural': 'Twitter Action Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
