# Generated by Django 4.2.16 on 2024-09-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='twitter_verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_verification_status',
            field=models.CharField(choices=[('NOT_CONFIRMED', 'Not Confirmed'), ('NOT_MATCHING_CRITERIA', 'Not Matching Criteria'), ('CONFIRMED', 'Confirmed')], default='NOT_CONFIRMED', max_length=256),
        ),
    ]
