# Generated by Django 4.2.16 on 2024-10-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='available_invites',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='invite_code',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='invite_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personal_invite_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
