# Generated by Django 4.2.16 on 2024-10-11 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_userprofile_available_invites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to='api.userprofile'),
        ),
    ]
