# Generated by Django 4.2.16 on 2024-09-26 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_userprofile_twitter_verification_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcompletion',
            name='action',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='api.task'),
        ),
        migrations.AlterUniqueTogether(
            name='taskcompletion',
            unique_together={('task', 'user', 'action')},
        ),
    ]
