# Generated by Django 4.2.16 on 2024-09-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_taskcompletion_action_alter_taskcompletion_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='twitter_oauth_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_oauth_token_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
