# Generated by Django 4.2.16 on 2024-10-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_twitter_screen_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='available_invites',
            field=models.IntegerField(default=2),
        ),
    ]
