# Generated by Django 4.2.16 on 2024-10-09 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile_available_invites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitecode',
            options={'ordering': ['-created_at']},
        ),
    ]
