# Generated by Django 4.2.16 on 2024-10-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_invited_by'),
        ('api', '0007_alter_invitecode_options'),
    ]

    operations = [
    ]
