# Generated by Django 4.2.16 on 2024-10-11 13:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20241011_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='invite_limit',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='personal_invite_code',
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='available_invites',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='invite_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='api.invitecode'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='api_task_status_2aef03_idx'),
        ),
    ]
