# Generated by Django 4.2.16 on 2024-10-12 05:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_remove_userprofile_invite_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='max_uses',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='uses_count',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='invitecode',
            name='used_by',
        ),
        migrations.AddField(
            model_name='invitecode',
            name='used_by',
            field=models.ManyToManyField(blank=True, related_name='used_invite_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
