# Generated by Django 4.2.16 on 2024-10-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='stripe_session_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
