# Generated by Django 4.2.16 on 2024-10-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_transaction_stripe_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='trial_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
