# Generated by Django 4.2.16 on 2024-10-21 03:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_userprofile_trial_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='available_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_tasks_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
