# Generated by Django 4.2.16 on 2024-10-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_userprofile_available_tasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_task_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tasks_created_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('REWARD', 'Reward'), ('REFUND', 'Refund'), ('SUBSCRIPTION', 'Subscription')], max_length=20),
        ),
    ]
