# Generated by Django 4.2.16 on 2024-10-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_task_tracking_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='tasks_created_today',
            new_name='daily_task_limit',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_task_created_at',
        ),
    ]
