# Generated by Django 4.2.16 on 2024-10-31 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0017_cleanup_duplicate_twitter_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscriptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email Subscription Type',
                'verbose_name_plural': 'Email Subscription Types',
            },
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body_html', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENDING', 'Sending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('successful_sends', models.IntegerField(default=0)),
                ('failed_sends', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subscription_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.emailsubscriptiontype')),
            ],
        ),
        migrations.CreateModel(
            name='UserEmailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_subscribed', models.BooleanField(default=True)),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.emailsubscriptiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'subscription_type')},
            },
        ),
    ]
