# Generated by Django 4.2.16 on 2024-11-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_emailsubscriptiontype_emailcampaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='completion_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
