# Generated by Django 4.2.16 on 2024-11-12 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0022_rename_task_completion_url_idx_api_taskcom_user_id_fedf95_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Social Network',
                'verbose_name_plural': 'Social Networks',
            },
        ),
        migrations.CreateModel(
            name='UserSocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_id', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(max_length=255)),
                ('profile_url', models.URLField(blank=True, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('NOT_VERIFIED', 'Not Verified'), ('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='NOT_VERIFIED', max_length=50)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('oauth_token', models.CharField(blank=True, max_length=255, null=True)),
                ('oauth_token_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('followers_count', models.IntegerField(default=0)),
                ('following_count', models.IntegerField(default=0)),
                ('posts_count', models.IntegerField(default=0)),
                ('account_created_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Social Profile',
                'verbose_name_plural': 'User Social Profiles',
            },
        ),
        migrations.RemoveIndex(
            model_name='taskcompletion',
            name='api_taskcom_user_id_fedf95_idx',
        ),
        migrations.AlterUniqueTogether(
            name='taskcompletion',
            unique_together={('task', 'user', 'action')},
        ),
        migrations.AddField(
            model_name='usersocialprofile',
            name='social_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.socialnetwork'),
        ),
        migrations.AddField(
            model_name='usersocialprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='taskcompletion',
            name='twitter_url',
        ),
        migrations.AddIndex(
            model_name='usersocialprofile',
            index=models.Index(fields=['user', 'social_network'], name='api_usersoc_user_id_ce2ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='usersocialprofile',
            index=models.Index(fields=['username'], name='api_usersoc_usernam_cfe8fe_idx'),
        ),
        migrations.AddIndex(
            model_name='usersocialprofile',
            index=models.Index(fields=['verification_status'], name='api_usersoc_verific_e4c7c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersocialprofile',
            unique_together={('user', 'social_network', 'username')},
        ),
    ]
