# Generated by Django 4.2.16 on 2024-11-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_ensure_taskcompletion_completed_at_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcompletion',
            name='is_auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='auto_actions_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_auto_action_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='taskcompletion',
            index=models.Index(fields=['is_auto', 'created_at'], name='api_taskcom_is_auto_9f4ced_idx'),
        ),
    ]
