# Generated by Django 4.2.16 on 2024-11-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_postcategory_posttag_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='send_email',
            field=models.BooleanField(default=False, verbose_name='Send email notification'),
        ),
    ]
