# Generated by Django 4.2.16 on 2024-12-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_create_social_networks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialnetwork',
            name='available_actions',
        ),
    ]
