# Generated by Django 4.2.16 on 2024-12-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_add_available_actions_to_socialnetwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='available_actions',
            field=models.ManyToManyField(related_name='social_networks', to='api.actiontype'),
        ),
    ]
