# Generated by Django 4.2.16 on 2024-12-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_link_social_networks_with_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='target_user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='TwitterUserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('twitter_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'twitter_user_mapping',
                'indexes': [models.Index(fields=['username'], name='twitter_use_usernam_f5d891_idx')],
            },
        ),
    ]
