# Generated by Django 4.2.16 on 2024-12-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_update_follow_tasks_twitter_ids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twitterserviceaccount',
            options={'ordering': ['last_used_at']},
        ),
        migrations.RemoveField(
            model_name='twitterserviceaccount',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='twitterserviceaccount',
            name='name',
        ),
        migrations.RemoveField(
            model_name='twitterserviceaccount',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='twitterserviceaccount',
            name='user_image_url',
        ),
        migrations.RemoveField(
            model_name='twitterserviceaccount',
            name='user_twitter_id',
        ),
        migrations.RemoveField(
            model_name='twitterserviceaccount',
            name='username',
        ),
        migrations.AddField(
            model_name='twitterserviceaccount',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='twitterserviceaccount',
            name='api_secret',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='twitterserviceaccount',
            name='bearer_token',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='twitterserviceaccount',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitterserviceaccount',
            name='rate_limit_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twitterserviceaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
