# Generated by Django 4.2.16 on 2024-12-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_twitterserviceaccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='email_send_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
