# Generated by Django 4.2.16 on 2025-01-20 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_paymenttransaction'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='taskcompletion',
            name='api_taskcom_is_auto_9f4ced_idx',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='twitter_url',
            new_name='post_url',
        ),
        migrations.RenameField(
            model_name='taskcompletion',
            old_name='twitter_url',
            new_name='post_url',
        ),
        migrations.RenameIndex(
            model_name='taskcompletion',
            new_name='api_taskcom_user_id_23d638_idx',
            old_name='tc_user_action_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='social_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.socialnetwork'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('LIKE', 'Like'), ('REPOST', 'Repost'), ('COMMENT', 'Comment'), ('FOLLOW', 'Follow'), ('SAVE', 'Save'), ('BOOST', 'Boost'), ('FAVORITE', 'Favorite'), ('REPLY', 'Reply'), ('CLAP', 'Clap'), ('RESTACK', 'Restack'), ('UPVOTE', 'Upvote'), ('DOWNVOTE', 'Downvote'), ('UP', 'Up'), ('DOWN', 'Down'), ('STAR', 'Star'), ('WATCH', 'Watch'), ('CONNECT', 'Connect'), ('UNICORN', 'Unicorn'), ('INSTALL', 'Install'), ('SHARE', 'Share')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['social_network', 'type'], name='api_task_social__9d4cda_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['post_url'], name='api_task_post_ur_40c055_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcompletion',
            index=models.Index(fields=['task', 'action'], name='api_taskcom_task_id_d339e7_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcompletion',
            index=models.Index(fields=['created_at'], name='api_taskcom_created_7f0677_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcompletion',
            index=models.Index(fields=['completed_at'], name='api_taskcom_complet_b206dc_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcompletion',
            index=models.Index(fields=['is_auto'], name='api_taskcom_is_auto_0e9f35_idx'),
        ),
    ]
