# Generated by Django 4.2.16 on 2025-01-20 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_remove_taskcompletion_api_taskcom_is_auto_9f4ced_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='social_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.socialnetwork'),
        ),
    ]
