# Generated by Django 4.2.16 on 2025-01-28 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0051_alter_task_social_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('i_dont_want_to_do_it', 'Just Hide'), ('not_available', 'Url Not Available'), ('not_working', 'Not Working')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Report',
                'verbose_name_plural': 'Task Reports',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'task')},
            },
        ),
    ]
