# Generated by Django 4.2.16 on 2025-01-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_taskreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='post_url',
            field=models.URLField(max_length=1000),
        ),
    ]
