# Generated by Django 4.2.16 on 2025-01-31 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0055_fix_taskcompletion_post_url_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscriptiontype',
            name='subscribe_all_users',
            field=models.BooleanField(default=False, help_text="If checked, all active users who haven't unsubscribed from any mailing will be subscribed", verbose_name='Subscribe all users'),
        ),
        migrations.AddField(
            model_name='emailsubscriptiontype',
            name='users_to_subscribe',
            field=models.ManyToManyField(blank=True, help_text='Select users to subscribe to this mailing type', related_name='subscription_types_to_subscribe', to=settings.AUTH_USER_MODEL, verbose_name='Users to subscribe'),
        ),
    ]
