# Generated by Django 4.2.16 on 2025-02-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_add_subscription_type_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='completed_tasks_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='game_rewards_claimed',
            field=models.IntegerField(default=0, help_text='Number of game rewards claimed by user'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_reward_at_task_count',
            field=models.IntegerField(default=0, help_text='Number of completed tasks when last reward was claimed'),
        ),
    ]
