# Generated by Django 4.2.16 on 2025-02-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_userprofile_completed_tasks_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bonus_tasks_completed',
            field=models.IntegerField(default=0, help_text='Number of bonus tasks completed'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_reward_at_task_count',
            field=models.IntegerField(default=0, help_text='Number of completed bonus tasks when last reward was claimed'),
        ),
    ]
