# Generated by Django 4.2.16 on 2025-02-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_paymenttransaction_last_webhook_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='attempt_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='last_payment_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='next_payment_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('TRIAL', 'Trial'), ('TRIAL_ENDED', 'Trial Ended'), ('ACTIVE', 'Active'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAST_DUE', 'Past Due')], default='PENDING', max_length=50),
        ),
    ]
