# Generated by Django 4.2.16 on 2025-02-12 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_paymenttransaction_attempt_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL Slug')),
                ('meta_title', models.CharField(max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.TextField(verbose_name='Meta Description')),
                ('h1', models.CharField(max_length=255, verbose_name='H1')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page',
                'verbose_name_plural': 'Landing Pages',
            },
        ),
        migrations.CreateModel(
            name='ActionLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main title of the landing page', max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(help_text='URL-friendly version of the title', max_length=255, unique=True, verbose_name='URL')),
                ('action', models.CharField(blank=True, help_text='Type of action for this landing page', max_length=50, null=True, verbose_name='Action')),
                ('short_description', models.TextField(help_text='Brief description for meta tags and previews', verbose_name='Short Description')),
                ('long_description', models.TextField(help_text='Full content of the landing page', verbose_name='Long Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_network', models.ForeignKey(blank=True, help_text='Related social network for this landing', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.socialnetwork', verbose_name='Social Network')),
            ],
            options={
                'verbose_name': 'Action Landing',
                'verbose_name_plural': 'Action Landings',
                'indexes': [models.Index(fields=['slug'], name='api_actionl_slug_92ad6a_idx'), models.Index(fields=['social_network', 'action'], name='api_actionl_social__89c74e_idx')],
            },
        ),
    ]
