# Generated by Django 4.2.16 on 2025-02-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_landing_actionlanding'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='subscription_period_type',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], help_text='Type of subscription period (monthly/annual)', max_length=20, null=True),
        ),
    ]
