# Generated by Django 4.2.16 on 2025-02-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_paymenttransaction_subscription_period_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='action',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Action'),
        ),
        migrations.AddField(
            model_name='landing',
            name='article_structure',
            field=models.TextField(blank=True, help_text='Structure of the article content', null=True, verbose_name='Article Structure'),
        ),
        migrations.AddField(
            model_name='landing',
            name='cluster_description',
            field=models.TextField(blank=True, help_text='Description of the SEO cluster', null=True, verbose_name='Cluster Description'),
        ),
        migrations.AddField(
            model_name='landing',
            name='cluster_name',
            field=models.CharField(blank=True, help_text='Name of the SEO cluster', max_length=255, null=True, verbose_name='Cluster Name'),
        ),
        migrations.AddField(
            model_name='landing',
            name='indexed_at',
            field=models.DateTimeField(blank=True, help_text='When this page was submitted to Google Indexing API', null=True, verbose_name='Indexed At'),
        ),
        migrations.AddField(
            model_name='landing',
            name='indexing_error',
            field=models.TextField(blank=True, help_text='Error message if indexing failed', null=True, verbose_name='Indexing Error'),
        ),
        migrations.AddField(
            model_name='landing',
            name='is_indexed',
            field=models.BooleanField(default=False, help_text='Whether this page was submitted to Google Indexing API', verbose_name='Indexed in Google'),
        ),
        migrations.AddField(
            model_name='landing',
            name='og_description',
            field=models.TextField(blank=True, help_text='Description for social media sharing', null=True, verbose_name='OG Description'),
        ),
        migrations.AddField(
            model_name='landing',
            name='og_title',
            field=models.CharField(blank=True, help_text='Title for social media sharing', max_length=255, null=True, verbose_name='OG Title'),
        ),
        migrations.AddField(
            model_name='landing',
            name='page_blocks',
            field=models.TextField(blank=True, help_text='Main blocks/sections of the page', null=True, verbose_name='Page Blocks'),
        ),
        migrations.AddField(
            model_name='landing',
            name='page_idea',
            field=models.TextField(blank=True, help_text='Main idea and purpose of the page', null=True, verbose_name='Page Idea'),
        ),
        migrations.AddField(
            model_name='landing',
            name='page_type',
            field=models.CharField(blank=True, help_text='Type of the landing page', max_length=50, null=True, verbose_name='Page Type'),
        ),
        migrations.AddField(
            model_name='landing',
            name='social_network',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Social Network'),
        ),
        migrations.AddField(
            model_name='landing',
            name='user_behavior',
            field=models.TextField(blank=True, help_text='Expected user behavior on the page', null=True, verbose_name='User Behavior'),
        ),
        migrations.AddIndex(
            model_name='landing',
            index=models.Index(fields=['slug'], name='api_landing_slug_d02b30_idx'),
        ),
        migrations.AddIndex(
            model_name='landing',
            index=models.Index(fields=['social_network', 'action'], name='api_landing_social__5ae0c2_idx'),
        ),
        migrations.AddIndex(
            model_name='landing',
            index=models.Index(fields=['is_indexed'], name='api_landing_is_inde_df444e_idx'),
        ),
    ]
