# Generated by Django 4.2.16 on 2025-02-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_landing_action_landing_article_structure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlanding',
            name='article_structure',
            field=models.TextField(blank=True, help_text='Structure of the article content', null=True, verbose_name='Article Structure'),
        ),
        migrations.AddField(
            model_name='actionlanding',
            name='cluster_description',
            field=models.TextField(blank=True, help_text='Description of the SEO cluster', null=True, verbose_name='Cluster Description'),
        ),
        migrations.AddField(
            model_name='actionlanding',
            name='cluster_name',
            field=models.CharField(blank=True, help_text='Name of the SEO cluster', max_length=255, null=True, verbose_name='Cluster Name'),
        ),
        migrations.AddField(
            model_name='actionlanding',
            name='content',
            field=models.TextField(blank=True, help_text='Main content of the page', null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='actionlanding',
            name='h1',
            field=models.CharField(blank=True, help_text='Main heading of the page', max_length=255, null=True, verbose_name='H1'),
        ),
        migrations.AddField(
            model_name='actionlanding',
            name='indexed_at',
            field=models.DateTimeField(blank=True, help_text='When this page was submitted to Google Indexing API', null=True, verbose_name='Indexed At'),
        ),
        migrations.AddField(
            model_name='actionlanding',
            name='indexing_error',
            field=models.TextField(blank=True, help_text='Error message if indexing failed', null=True, verbose_name='Indexing Error'),
        ),
        migrations.AddField(
            model_name='actionlanding',
            name='is_indexed',
            field=models.BooleanField(default=False, help_text='Whether this page was submitted to Google Indexing API', verbose_name='Indexed in Google'),
        ),
        migrations.AddField(
            model_name='actionlanding',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Description for search engines', null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='actionlanding',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Title for search engines', max_length=255, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='actionlanding',
            name='og_description',
            field=models.TextField(blank=True, help_text='Description for social media sharing', null=True, verbose_name='OG Description'),
        ),
        migrations.AddField(
            model_name='actionlanding',
            name='og_title',
            field=models.CharField(blank=True, help_text='Title for social media sharing', max_length=255, null=True, verbose_name='OG Title'),
        ),
        migrations.AddField(
            model_name='actionlanding',
            name='page_blocks',
            field=models.TextField(blank=True, help_text='Main blocks/sections of the page', null=True, verbose_name='Page Blocks'),
        ),
        migrations.AddField(
            model_name='actionlanding',
            name='page_idea',
            field=models.TextField(blank=True, help_text='Main idea and purpose of the page', null=True, verbose_name='Page Idea'),
        ),
        migrations.AddField(
            model_name='actionlanding',
            name='page_type',
            field=models.CharField(blank=True, help_text='Type of the landing page', max_length=50, null=True, verbose_name='Page Type'),
        ),
        migrations.AddField(
            model_name='actionlanding',
            name='user_behavior',
            field=models.TextField(blank=True, help_text='Expected user behavior on the page', null=True, verbose_name='User Behavior'),
        ),
        migrations.AddIndex(
            model_name='actionlanding',
            index=models.Index(fields=['is_indexed'], name='api_actionl_is_inde_fb9856_idx'),
        ),
    ]
