# Generated by Django 4.2.16 on 2025-02-21 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_delete_transaction'),
        ('api', '0064_actionlanding_article_structure_and_more'),
    ]

    operations = [
    ]
