# Generated by Django 4.2.16 on 2025-03-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_merge_20250221_0230'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='taskcompletion',
            name='api_taskcom_user_id_23d638_idx',
        ),
        migrations.RemoveIndex(
            model_name='taskcompletion',
            name='api_taskcom_task_id_d339e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='taskcompletion',
            name='api_taskcom_complet_b206dc_idx',
        ),
        migrations.RemoveIndex(
            model_name='taskcompletion',
            name='api_taskcom_is_auto_0e9f35_idx',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country_code',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code', max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='taskcompletion',
            index=models.Index(fields=['user', 'task'], name='api_taskcom_user_id_2b5dbd_idx'),
        ),
    ]
