# Generated by Django 4.2.16 on 2025-03-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_remove_taskcompletion_api_taskcom_user_id_23d638_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deletion_reason',
            field=models.CharField(blank=True, choices=[('LINK_UNAVAILABLE', 'Link Unavailable'), ('COMMUNITY_RULES', 'Violates Community Rules')], help_text='Reason for task deletion', max_length=50, null=True),
        ),
    ]
