# Generated by Django 4.2.16 on 2025-03-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_task_deletion_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='pending_notification_sent',
            field=models.BooleanField(default=False, help_text='Whether notification about pending payment was sent'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='pending_notification_sent_at',
            field=models.DateTimeField(blank=True, help_text='When notification about pending payment was sent', null=True),
        ),
    ]
