# Generated by Django 4.2.16 on 2025-03-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_paymenttransaction_pending_notification_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deletion_reason',
            field=models.CharField(blank=True, choices=[('LINK_UNAVAILABLE', 'Link Unavailable'), ('COMMUNITY_RULES', 'Violates Community Rules'), ('USER_REQUEST', 'User Request'), ('DOUBLE_ACCOUNT', 'Double Account')], help_text='Reason for task deletion', max_length=50, null=True),
        ),
    ]
