# Generated by Django 4.2.16 on 2025-04-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_add_invited_by_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chosen_country',
            field=models.CharField(blank=True, help_text='Country chosen by user (ISO 3166-1 alpha-2 country code)', max_length=10, null=True, verbose_name='Chosen Country'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_affiliate_partner',
            field=models.BooleanField(default=False, help_text='Whether user is an affiliate partner', verbose_name='Affiliate Partner'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_ambassador',
            field=models.BooleanField(default=False, help_text='Whether user is an ambassador', verbose_name='Ambassador'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='paypal_address',
            field=models.EmailField(blank=True, help_text='PayPal email address for payments', max_length=255, null=True, verbose_name='PayPal Address'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_client_id',
            field=models.CharField(blank=True, help_text='Stripe client identifier', max_length=255, null=True, verbose_name='Stripe Client ID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='usdt_address',
            field=models.CharField(blank=True, help_text='USDT wallet address for payments', max_length=255, null=True, verbose_name='USDT Address'),
        ),
    ]
