# Generated by Django 4.2.16 on 2025-06-12 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0071_userprofile_chosen_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, help_text='Amount to withdraw in USD', max_digits=10, verbose_name='Amount (USD)')),
                ('points_sold', models.IntegerField(help_text='Number of points converted to USD', verbose_name='Points Sold')),
                ('withdrawal_method', models.CharField(choices=[('PAYPAL', 'PayPal'), ('USDT', 'USDT')], max_length=10, verbose_name='Withdrawal Method')),
                ('withdrawal_address', models.CharField(help_text='PayPal email or USDT wallet address', max_length=255, verbose_name='Withdrawal Address')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the withdrawal was processed', null=True, verbose_name='Processed At')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for administrators', null=True, verbose_name='Admin Notes')),
                ('transaction_id', models.CharField(blank=True, help_text='External transaction ID (PayPal transaction ID, USDT tx hash, etc.)', max_length=255, null=True, verbose_name='Transaction ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Withdrawal',
                'verbose_name_plural': 'Withdrawals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='api_withdra_user_id_8b639f_idx'), models.Index(fields=['created_at'], name='api_withdra_created_3a821a_idx'), models.Index(fields=['withdrawal_method'], name='api_withdra_withdra_e061f6_idx'), models.Index(fields=['status'], name='api_withdra_status_d3e117_idx')],
            },
        ),
    ]
