# Generated by Django 4.2.16 on 2025-06-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('TRIAL', 'Trial'), ('TRIAL_ENDED', 'Trial Ended'), ('ACTIVE', 'Active'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAST_DUE', 'Past Due'), ('SETUP_COMPLETED', 'Setup Completed')], default='PENDING', max_length=50),
        ),
    ]
