# Generated by Django 4.2.16 on 2025-07-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_add_setup_completed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deletion_reason',
            field=models.CharField(blank=True, choices=[('LINK_UNAVAILABLE', 'Link Unavailable'), ('COMMUNITY_RULES', 'Violates Community Rules'), ('USER_REQUEST', 'User Request'), ('DOUBLE_ACCOUNT', 'Double Account'), ('AUTO_CLOSE_24H', 'Auto closed after 24h (system)')], help_text='Reason for task deletion', max_length=50, null=True),
        ),
    ]
