# Generated by Django 4.2.16 on 2025-07-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_alter_task_deletion_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='If checked, this task will always be shown at the top of the list', verbose_name='Pin at the top'),
        ),
    ]
