# Generated by Django 4.2.16 on 2025-07-24 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0075_task_is_pinned'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_country', models.CharField(blank=True, help_text='Country chosen by user (ISO 3166-1 alpha-2 code)', max_length=10, null=True)),
                ('account_type', models.CharField(blank=True, help_text='Account type: business or individual', max_length=20, null=True)),
                ('social_networks', models.JSONField(blank=True, help_text='List of selected social networks (codes)', null=True)),
                ('actions', models.JSONField(blank=True, help_text='Dict: {social_network_code: [action_codes]}', null=True)),
                ('goal_description', models.TextField(blank=True, help_text='User description after social networks and actions', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding Progress',
                'verbose_name_plural': 'Onboarding Progresses',
            },
        ),
    ]
