# Generated by Django 4.2.16 on 2025-07-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_onboardingprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlanding',
            name='redirect_url',
            field=models.CharField(blank=True, help_text='If set, this landing will redirect (301) to the specified URL', max_length=512, null=True, verbose_name='301 Redirect URL'),
        ),
    ]
