# Generated by Django 4.2.16 on 2025-07-27 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0077_actionlanding_redirect_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions_count', models.IntegerField(help_text='Number of actions in the task')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating from 1 to 5')),
                ('comment_1', models.TextField(blank=True, help_text='Comment for rating 1', null=True)),
                ('comment_2', models.TextField(blank=True, help_text='Comment for rating 2', null=True)),
                ('comment_3', models.TextField(blank=True, help_text='Comment for rating 3', null=True)),
                ('comment_4', models.TextField(blank=True, help_text='Comment for rating 4', null=True)),
                ('comment_5', models.TextField(blank=True, help_text='Comment for rating 5', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(help_text='Action type', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.actiontype')),
                ('social_network', models.ForeignKey(help_text='Social network', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.socialnetwork')),
                ('task', models.ForeignKey(help_text='Task ID', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.task')),
                ('user', models.ForeignKey(help_text='Firebase UID (User)', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'indexes': [models.Index(fields=['user', 'task', 'social_network', 'action'], name='api_review_user_id_c54860_idx')],
            },
        ),
    ]
