# Generated by Django 4.2.16 on 2025-08-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlanding',
            name='faq',
            field=models.TextField(blank=True, help_text='FAQ section as JSON text', null=True, verbose_name='FAQ'),
        ),
        migrations.AddField(
            model_name='actionlanding',
            name='how_it_works',
            field=models.JSONField(blank=True, help_text='List of up to 9 steps, each with title, description, image_url', null=True, verbose_name='How It Works'),
        ),
        migrations.AddField(
            model_name='actionlanding',
            name='key_features',
            field=models.JSONField(blank=True, help_text='List of up to 9 key features, each with title, description, image_url', null=True, verbose_name='Key Features'),
        ),
    ]
