# Generated by Django 4.2.16 on 2025-08-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_alter_actionlanding_long_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionlanding',
            name='article_structure',
        ),
        migrations.RemoveField(
            model_name='actionlanding',
            name='cluster_description',
        ),
        migrations.RemoveField(
            model_name='actionlanding',
            name='cluster_name',
        ),
        migrations.RemoveField(
            model_name='actionlanding',
            name='page_blocks',
        ),
        migrations.RemoveField(
            model_name='actionlanding',
            name='page_idea',
        ),
        migrations.RemoveField(
            model_name='actionlanding',
            name='user_behavior',
        ),
    ]
