# Generated by Django 4.2.16 on 2025-08-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_remove_actionlanding_article_structure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionlanding',
            name='h1',
        ),
        migrations.AlterField(
            model_name='actionlanding',
            name='title',
            field=models.CharField(help_text='Main title of the landing page', max_length=255, verbose_name='Title / H1'),
        ),
    ]
