# Generated by Django 4.2.16 on 2025-08-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_remove_actionlanding_h1_alter_actionlanding_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionlanding',
            name='faq',
        ),
        migrations.RemoveField(
            model_name='actionlanding',
            name='how_it_works',
        ),
        migrations.RemoveField(
            model_name='actionlanding',
            name='key_features',
        ),
        migrations.AddField(
            model_name='actionlanding',
            name='article_structure',
            field=models.TextField(blank=True, help_text='Structure of the article content', null=True, verbose_name='Article Structure'),
        ),
        migrations.AddField(
            model_name='actionlanding',
            name='cluster_description',
            field=models.TextField(blank=True, help_text='Description of the SEO cluster', null=True, verbose_name='Cluster Description'),
        ),
        migrations.AddField(
            model_name='actionlanding',
            name='cluster_name',
            field=models.CharField(blank=True, help_text='Name of the SEO cluster', max_length=255, null=True, verbose_name='Cluster Name'),
        ),
        migrations.AddField(
            model_name='actionlanding',
            name='h1',
            field=models.CharField(blank=True, help_text='Main heading of the page', max_length=255, null=True, verbose_name='H1'),
        ),
        migrations.AddField(
            model_name='actionlanding',
            name='page_blocks',
            field=models.TextField(blank=True, help_text='Main blocks/sections of the page', null=True, verbose_name='Page Blocks'),
        ),
        migrations.AddField(
            model_name='actionlanding',
            name='page_idea',
            field=models.TextField(blank=True, help_text='Main idea and purpose of the page', null=True, verbose_name='Page Idea'),
        ),
        migrations.AddField(
            model_name='actionlanding',
            name='user_behavior',
            field=models.TextField(blank=True, help_text='Expected user behavior on the page', null=True, verbose_name='User Behavior'),
        ),
        migrations.AlterField(
            model_name='actionlanding',
            name='long_description',
            field=models.TextField(help_text='Full content of the landing page', verbose_name='Long Description'),
        ),
        migrations.AlterField(
            model_name='actionlanding',
            name='short_description',
            field=models.TextField(help_text='Brief description for meta tags and previews', verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='actionlanding',
            name='title',
            field=models.CharField(help_text='Main title of the landing page', max_length=255, verbose_name='Title'),
        ),
    ]
