# Generated by Django 4.2.16 on 2025-08-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_remove_actionlanding_faq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlanding',
            name='long_description',
            field=models.TextField(blank=True, help_text='Full content of the landing page', null=True, verbose_name='Long Description'),
        ),
        migrations.AlterField(
            model_name='actionlanding',
            name='short_description',
            field=models.TextField(blank=True, help_text='Brief description for meta tags and previews', null=True, verbose_name='Short Description'),
        ),
    ]
