# Generated by Django 4.2.16 on 2025-09-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_alter_actionlanding_long_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionlanding',
            name='article_structure',
        ),
        migrations.RemoveField(
            model_name='actionlanding',
            name='cluster_description',
        ),
        migrations.RemoveField(
            model_name='actionlanding',
            name='cluster_name',
        ),
        migrations.RemoveField(
            model_name='actionlanding',
            name='og_description',
        ),
        migrations.RemoveField(
            model_name='actionlanding',
            name='og_title',
        ),
        migrations.RemoveField(
            model_name='actionlanding',
            name='page_idea',
        ),
        migrations.RemoveField(
            model_name='actionlanding',
            name='user_behavior',
        ),
        migrations.AddField(
            model_name='actionlanding',
            name='faq',
            field=models.JSONField(blank=True, help_text='List of Q&A items, e.g. [{"q": "Question", "a": "Answer"}]', null=True, verbose_name='FAQ'),
        ),
    ]
