# Generated by Django 4.2.16 on 2025-09-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_remove_actionlanding_article_structure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersocialprofile',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('NO_EMOJI', 'No Emoji'), ('DOES_NOT_MEET_CRITERIA', 'Profile does not meet criteria')], help_text='Reason for rejection if profile was rejected', max_length=50, null=True),
        ),
    ]
