# Generated by Django 4.2.16 on 2025-09-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_add_rejection_reason_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bonus_actions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='bonus_actions_completed',
            field=models.IntegerField(default=0),
        ),
    ]
