# Generated by Django 4.2.16 on 2025-09-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_task_bonus_actions_task_bonus_actions_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='longview',
            field=models.BooleanField(default=False, help_text='If checked, show extended task view in UI', verbose_name='Long view'),
        ),
        migrations.AddField(
            model_name='task',
            name='meaningful_comment',
            field=models.BooleanField(default=False, help_text='If enabled, use provided comments list for users to post', verbose_name='Meaningful comment'),
        ),
        migrations.AddField(
            model_name='task',
            name='meaningful_comments',
            field=models.JSONField(blank=True, help_text='JSON array of comments: [{"id": "unique", "text": "comment text", "sent": false}]', null=True, verbose_name='Comments list (JSON)'),
        ),
    ]
