# Generated by Django 4.2.16 on 2025-10-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_task_longview_task_meaningful_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='is_task_purchase',
            field=models.BooleanField(default=False, help_text='Whether this payment is for task creation purchase', verbose_name='Task Purchase'),
        ),
    ]
