# Generated by Django 4.2.16 on 2025-10-22 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_paymenttransaction_is_task_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='task',
            field=models.ForeignKey(blank=True, help_text='Task created after successful payment', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.task', verbose_name='Created Task'),
        ),
    ]
