# Generated by Django 4.2.16 on 2025-10-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_add_task_to_payment_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='landing_url',
            field=models.CharField(blank=True, help_text='First page user visited on the site', max_length=1000, null=True, verbose_name='Landing URL'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referrer_timestamp',
            field=models.DateTimeField(blank=True, help_text='When user first visited the site', null=True, verbose_name='Referrer Timestamp'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referrer_url',
            field=models.CharField(blank=True, help_text='URL where user came from', max_length=1000, null=True, verbose_name='Referrer URL'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referrer_user_agent',
            field=models.TextField(blank=True, help_text='User agent when user first visited', null=True, verbose_name='Referrer User Agent'),
        ),
    ]
