# Generated by Django 4.2.16 on 2025-10-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_add_referrer_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='device_type',
            field=models.CharField(blank=True, help_text='Device category: mobile, tablet, desktop', max_length=50, null=True, verbose_name='Device Type'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='os_name',
            field=models.CharField(blank=True, help_text='Operating system name', max_length=50, null=True, verbose_name='OS Name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='os_version',
            field=models.CharField(blank=True, help_text='Operating system version', max_length=50, null=True, verbose_name='OS Version'),
        ),
    ]
