# Generated by Django 4.2.16 on 2025-10-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_add_device_os_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='device_type',
            field=models.CharField(blank=True, help_text='Device category: mobile, tablet, desktop', max_length=128, null=True, verbose_name='Device Type'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='landing_url',
            field=models.CharField(blank=True, help_text='First page user visited on the site', max_length=2048, null=True, verbose_name='Landing URL'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='os_name',
            field=models.CharField(blank=True, help_text='Operating system name', max_length=128, null=True, verbose_name='OS Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='os_version',
            field=models.CharField(blank=True, help_text='Operating system version', max_length=128, null=True, verbose_name='OS Version'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='referrer_url',
            field=models.CharField(blank=True, help_text='URL where user came from', max_length=2048, null=True, verbose_name='Referrer URL'),
        ),
    ]
