# Generated by Django 4.2.16 on 2025-10-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_widen_referrer_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='device_type',
            field=models.TextField(blank=True, help_text='Device category: mobile, tablet, desktop', null=True, verbose_name='Device Type'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='landing_url',
            field=models.TextField(blank=True, help_text='First page user visited on the site', null=True, verbose_name='Landing URL'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='os_name',
            field=models.TextField(blank=True, help_text='Operating system name', null=True, verbose_name='OS Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='os_version',
            field=models.TextField(blank=True, help_text='Operating system version', null=True, verbose_name='OS Version'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='referrer_url',
            field=models.TextField(blank=True, help_text='URL where user came from', null=True, verbose_name='Referrer URL'),
        ),
    ]
