# Generated by Django 4.2.16 on 2025-11-07 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_alter_userprofile_device_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main title of the buy landing page', max_length=255, verbose_name='Title')),
                ('description', models.TextField(help_text='Full description of the buy landing page', verbose_name='Description')),
                ('short_description', models.TextField(help_text='Brief description for previews', verbose_name='Short Description')),
                ('slug', models.SlugField(help_text='URL-friendly identifier for this landing', max_length=255, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(help_text='Type of action for this buy landing page', on_delete=django.db.models.deletion.CASCADE, related_name='buy_landings', to='api.actiontype', verbose_name='Action')),
                ('social_network', models.ForeignKey(help_text='Related social network for this buy landing', on_delete=django.db.models.deletion.CASCADE, related_name='buy_landings', to='api.socialnetwork', verbose_name='Social Network')),
            ],
            options={
                'verbose_name': 'Buy Landing',
                'verbose_name_plural': 'Buy Landings',
                'indexes': [models.Index(fields=['slug'], name='api_buyland_slug_f577f1_idx'), models.Index(fields=['social_network', 'action'], name='api_buyland_social__b595fb_idx')],
                'unique_together': {('social_network', 'action')},
            },
        ),
    ]
