# Generated by Django 4.2.16 on 2025-11-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_buylanding'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontype',
            name='name_plural',
            field=models.CharField(blank=True, help_text='Plural form of the action name (e.g., "Likes", "Followers")', max_length=50, null=True, verbose_name='Name Plural'),
        ),
    ]
