# Generated by Django 4.2.16 on 2025-11-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_actiontype_name_plural'),
    ]

    operations = [
        migrations.AddField(
            model_name='buylanding',
            name='indexed_at',
            field=models.DateTimeField(blank=True, help_text='When this page was submitted to Google Indexing API', null=True, verbose_name='Indexed At'),
        ),
        migrations.AddField(
            model_name='buylanding',
            name='indexing_error',
            field=models.TextField(blank=True, help_text='Error message if indexing failed', null=True, verbose_name='Indexing Error'),
        ),
        migrations.AddField(
            model_name='buylanding',
            name='is_indexed',
            field=models.BooleanField(default=False, help_text='Whether this page was submitted to Google Indexing API', verbose_name='Indexed in Google'),
        ),
        migrations.AddIndex(
            model_name='buylanding',
            index=models.Index(fields=['is_indexed'], name='api_buyland_is_inde_693171_idx'),
        ),
    ]
