# Generated by Django 4.2.16 on 2025-11-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_buylanding_indexed_at_buylanding_indexing_error_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comment_1',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comment_2',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comment_3',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comment_4',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comment_5',
        ),
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, help_text='User comment for the review', null=True),
        ),
    ]
