# Generated by Django 4.2.16 on 2025-11-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_remove_review_comment_1_remove_review_comment_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buylanding',
            name='h1',
            field=models.CharField(blank=True, help_text='Main heading of the page', max_length=255, null=True, verbose_name='H1'),
        ),
    ]
