# Generated by Django 4.2.16 on 2025-11-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_buylanding_h1'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='black_friday_subscribed',
            field=models.BooleanField(default=False, help_text='Whether user subscribed to Black Friday deal notifications', verbose_name='Black Friday Subscribed'),
        ),
    ]
