# Generated by Django 4.2.16 on 2025-12-17 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0100_userprofile_black_friday_subscribed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(db_index=True, help_text='Hashed API key for verification', max_length=128, unique=True)),
                ('name', models.CharField(blank=True, help_text='Optional name/description for the API key', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the API key is active')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time the API key was used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the API key was created')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for the API key', null=True)),
                ('user', models.ForeignKey(help_text='User who owns this API key', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key_hash', 'is_active'], name='api_apikey_key_has_af89f3_idx'), models.Index(fields=['user', 'is_active'], name='api_apikey_user_id_90f679_idx')],
            },
        ),
    ]
