# Generated by Django 4.2.16 on 2025-12-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, choices=[('ENGAGEMENT', 'Engagement'), ('CROWD', 'Crowd')], help_text='Type of task: Engagement or Crowd', max_length=20, null=True, verbose_name='Task Type'),
        ),
        migrations.AlterField(
            model_name='usersocialprofile',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('NO_EMOJI', 'No Emoji'), ('DOES_NOT_MEET_CRITERIA', 'Profile does not meet criteria'), ('URL_UNAVAILABLE', 'URL Unavailable')], help_text='Reason for rejection if profile was rejected', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_type'], name='api_task_task_ty_5a65cd_idx'),
        ),
    ]
