# Generated by Django 4.2.16 on 2025-12-26 03:19

from django.db import migrations


def set_default_task_type(apps, schema_editor):
    """Устанавливает 'ENGAGEMENT' для всех существующих заданий"""
    Task = apps.get_model('api', 'Task')
    Task.objects.filter(task_type__isnull=True).update(task_type='ENGAGEMENT')


def reverse_set_default_task_type(apps, schema_editor):
    """Откатывает изменения - устанавливает NULL для всех заданий с 'ENGAGEMENT'"""
    Task = apps.get_model('api', 'Task')
    Task.objects.filter(task_type='ENGAGEMENT').update(task_type=None)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_task_task_type_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_task_type, reverse_set_default_task_type),
    ]
