# Generated by Django 4.2.16 on 2025-12-26 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_set_default_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Text of the comment', verbose_name='Comment Text')),
                ('sent', models.BooleanField(default=False, help_text='Whether this comment has been used/sent', verbose_name='Sent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('task', models.ForeignKey(help_text='Task this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='crowd_tasks', to='api.task', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Crowd Task',
                'verbose_name_plural': 'Crowd Tasks',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['task', 'sent'], name='api_crowdta_task_id_708047_idx'), models.Index(fields=['created_at'], name='api_crowdta_created_d99945_idx')],
            },
        ),
    ]
