# Generated by Django 4.2.16 on 2025-12-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_add_crowdtask_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdtask',
            name='confirmed_by_parser',
            field=models.BooleanField(default=False, help_text='Whether this task was confirmed by parser', verbose_name='Confirmed by Parser'),
        ),
        migrations.AddField(
            model_name='crowdtask',
            name='confirmed_by_user',
            field=models.BooleanField(default=False, help_text='Whether this task was confirmed by user', verbose_name='Confirmed by User'),
        ),
        migrations.AddField(
            model_name='crowdtask',
            name='parser_log',
            field=models.TextField(blank=True, help_text='Log message from parser verification', null=True, verbose_name='Parser Log'),
        ),
        migrations.AddField(
            model_name='crowdtask',
            name='status',
            field=models.CharField(choices=[('SEARCHING', 'Searching'), ('IN_PROGRESS', 'In Progress'), ('PENDING_REVIEW', 'Pending Review'), ('COMPLETED', 'Completed')], default='SEARCHING', help_text='Status of the crowd task', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='crowdtask',
            name='url',
            field=models.URLField(blank=True, help_text='URL to verify task completion', max_length=1000, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='crowdtask',
            name='user_log',
            field=models.TextField(blank=True, help_text='Log message from user verification', null=True, verbose_name='User Log'),
        ),
        migrations.AddIndex(
            model_name='crowdtask',
            index=models.Index(fields=['task', 'status'], name='api_crowdta_task_id_ae3113_idx'),
        ),
        migrations.AddIndex(
            model_name='crowdtask',
            index=models.Index(fields=['confirmed_by_parser'], name='api_crowdta_confirm_e55b83_idx'),
        ),
        migrations.AddIndex(
            model_name='crowdtask',
            index=models.Index(fields=['confirmed_by_user'], name='api_crowdta_confirm_42898c_idx'),
        ),
    ]
