# Generated by Django 4.2.16 on 2025-12-26 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0105_add_crowdtask_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User who assigned this task to PENDING_REVIEW status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_crowd_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AddIndex(
            model_name='crowdtask',
            index=models.Index(fields=['assigned_to', 'status'], name='api_crowdta_assigne_96baa4_idx'),
        ),
    ]
