# Generated by Django 4.2.16 on 2025-12-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_add_faq_and_reviews_section_titles_to_actionlanding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlanding',
            name='how_it_works',
            field=models.JSONField(blank=True, help_text='JSON structure: [{"title": "Step Title", "text": "Step description text", "image": "image_url"}]', null=True, verbose_name='How It Works'),
        ),
        migrations.AlterField(
            model_name='actionlanding',
            name='why_upvote_club_best',
            field=models.JSONField(blank=True, help_text='JSON structure: [{"title": "Feature title", "text": "Feature description", "image": "image_url"}]', null=True, verbose_name='Why Upvote Club Best'),
        ),
    ]
