# Generated by Django 4.2.16 on 2026-01-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_alter_actionlanding_how_it_works_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buylanding',
            name='reviews',
            field=models.ManyToManyField(blank=True, help_text='Select reviews to display on this buy landing', related_name='buy_landings', to='api.review', verbose_name='Reviews'),
        ),
    ]
