# Generated by Django 4.2.16 on 2026-01-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_add_welcome_and_task_creation_email_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='promo_email_sent',
            field=models.BooleanField(default=False, help_text='Whether promotional campaign email was sent (for ProductHunt tasks)', verbose_name='Promo email sent'),
        ),
    ]
