# Generated by Django 4.2.16 on 2026-01-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_task_promo_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='buylanding',
            name='faq',
            field=models.JSONField(blank=True, default=list, help_text='FAQ items: [{"q": "How long does delivery take?", "a": "Usually 1-24 hours..."}]', verbose_name='FAQ'),
        ),
        migrations.AddField(
            model_name='buylanding',
            name='faq_section_title',
            field=models.CharField(blank=True, default='Frequently Asked Questions', help_text='Title for FAQ section', max_length=255, null=True, verbose_name='FAQ Section Title'),
        ),
        migrations.AddField(
            model_name='buylanding',
            name='how_it_works',
            field=models.JSONField(blank=True, default=list, help_text='List of how it works items: [{"emoji": "🧗\u200d♂️", "title": "Real people...", "text": "We are..."}]', verbose_name='How It Works'),
        ),
        migrations.AddField(
            model_name='buylanding',
            name='how_it_works_title',
            field=models.CharField(blank=True, default='How It Works?', help_text='Title for "How It Works" section', max_length=255, null=True, verbose_name='How It Works Title'),
        ),
        migrations.AddField(
            model_name='buylanding',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO description for search engines', null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='buylanding',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title for search engines', max_length=255, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='buylanding',
            name='og_description',
            field=models.TextField(blank=True, help_text='Open Graph description for social media sharing', null=True, verbose_name='OG Description'),
        ),
        migrations.AddField(
            model_name='buylanding',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title for social media sharing', max_length=255, null=True, verbose_name='OG Title'),
        ),
        migrations.AddField(
            model_name='buylanding',
            name='price_per_action',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Price in points for one action (e.g., 0.45 for Twitter like, 2.00 for ProductHunt upvote)', max_digits=10, verbose_name='Price Per Action'),
        ),
        migrations.AddField(
            model_name='buylanding',
            name='quantity_steps',
            field=models.JSONField(blank=True, default=list, help_text='Available quantity options, e.g., [2, 5, 10, 20, 50, 100]', verbose_name='Quantity Steps'),
        ),
        migrations.AddField(
            model_name='buylanding',
            name='reviews_section_title',
            field=models.CharField(blank=True, default='What Our Customers Say', help_text='Title for reviews section', max_length=255, null=True, verbose_name='Reviews Section Title'),
        ),
    ]
