# Generated by Django 4.2.16 on 2026-01-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_buylanding_faq_buylanding_faq_section_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheEntry',
            fields=[
                ('cache_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('expires', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Cache Entry',
                'verbose_name_plural': 'Cache Entries',
                'db_table': 'django_cache_table',
                'managed': False,
            },
        ),
    ]
